/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package net.chrizzly.csharp4netbeans.filetypes.cs.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ABSTRACT = 8;
  /** RegularExpression Id. */
  int AS = 9;
  /** RegularExpression Id. */
  int BASE = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int BYTE = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int CATCH = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int CHECKED = 17;
  /** RegularExpression Id. */
  int CLASS = 18;
  /** RegularExpression Id. */
  int CONST = 19;
  /** RegularExpression Id. */
  int CONTINUE = 20;
  /** RegularExpression Id. */
  int DECIMAL = 21;
  /** RegularExpression Id. */
  int _DEFAULT = 22;
  /** RegularExpression Id. */
  int DELEGATE = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int ENUM = 27;
  /** RegularExpression Id. */
  int EVENT = 28;
  /** RegularExpression Id. */
  int EXPLICIT = 29;
  /** RegularExpression Id. */
  int EXTERN = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FINALLY = 32;
  /** RegularExpression Id. */
  int FIXED = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int FOREACH = 36;
  /** RegularExpression Id. */
  int GET = 37;
  /** RegularExpression Id. */
  int GOTO = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int IMPLICIT = 40;
  /** RegularExpression Id. */
  int IN = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int INTERFACE = 43;
  /** RegularExpression Id. */
  int INTERNAL = 44;
  /** RegularExpression Id. */
  int IS = 45;
  /** RegularExpression Id. */
  int LOCK = 46;
  /** RegularExpression Id. */
  int LONG = 47;
  /** RegularExpression Id. */
  int NAMESPACE = 48;
  /** RegularExpression Id. */
  int NEW = 49;
  /** RegularExpression Id. */
  int NULL = 50;
  /** RegularExpression Id. */
  int OBJECT = 51;
  /** RegularExpression Id. */
  int OPERATOR = 52;
  /** RegularExpression Id. */
  int OUT = 53;
  /** RegularExpression Id. */
  int OVERRIDE = 54;
  /** RegularExpression Id. */
  int PARAMS = 55;
  /** RegularExpression Id. */
  int PARTIAL = 56;
  /** RegularExpression Id. */
  int PRIVATE = 57;
  /** RegularExpression Id. */
  int PROTECTED = 58;
  /** RegularExpression Id. */
  int PUBLIC = 59;
  /** RegularExpression Id. */
  int READONLY = 60;
  /** RegularExpression Id. */
  int REF = 61;
  /** RegularExpression Id. */
  int RETURN = 62;
  /** RegularExpression Id. */
  int SBYTE = 63;
  /** RegularExpression Id. */
  int SEALED = 64;
  /** RegularExpression Id. */
  int SET = 65;
  /** RegularExpression Id. */
  int SHORT = 66;
  /** RegularExpression Id. */
  int SIZEOF = 67;
  /** RegularExpression Id. */
  int STACKALLOC = 68;
  /** RegularExpression Id. */
  int STATIC = 69;
  /** RegularExpression Id. */
  int STRING = 70;
  /** RegularExpression Id. */
  int STRUCT = 71;
  /** RegularExpression Id. */
  int SWITCH = 72;
  /** RegularExpression Id. */
  int THIS = 73;
  /** RegularExpression Id. */
  int THROW = 74;
  /** RegularExpression Id. */
  int TRUE = 75;
  /** RegularExpression Id. */
  int TRY = 76;
  /** RegularExpression Id. */
  int TYPEOF = 77;
  /** RegularExpression Id. */
  int UINT = 78;
  /** RegularExpression Id. */
  int ULONG = 79;
  /** RegularExpression Id. */
  int UNCHECKED = 80;
  /** RegularExpression Id. */
  int UNSAFE = 81;
  /** RegularExpression Id. */
  int USHORT = 82;
  /** RegularExpression Id. */
  int USING = 83;
  /** RegularExpression Id. */
  int VAR = 84;
  /** RegularExpression Id. */
  int VIRTUAL = 85;
  /** RegularExpression Id. */
  int VOID = 86;
  /** RegularExpression Id. */
  int VOLATILE = 87;
  /** RegularExpression Id. */
  int WHILE = 88;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 89;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 90;
  /** RegularExpression Id. */
  int HEX_LITERAL = 91;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 92;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 93;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 94;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 95;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 96;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 97;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 98;
  /** RegularExpression Id. */
  int STRING_LITERAL = 99;
  /** RegularExpression Id. */
  int IDENTIFIER = 100;
  /** RegularExpression Id. */
  int LETTER = 101;
  /** RegularExpression Id. */
  int PART_LETTER = 102;
  /** RegularExpression Id. */
  int LPAREN = 103;
  /** RegularExpression Id. */
  int RPAREN = 104;
  /** RegularExpression Id. */
  int LBRACE = 105;
  /** RegularExpression Id. */
  int RBRACE = 106;
  /** RegularExpression Id. */
  int LBRACKET = 107;
  /** RegularExpression Id. */
  int RBRACKET = 108;
  /** RegularExpression Id. */
  int SEMICOLON = 109;
  /** RegularExpression Id. */
  int COMMA = 110;
  /** RegularExpression Id. */
  int DOT = 111;
  /** RegularExpression Id. */
  int AT = 112;
  /** RegularExpression Id. */
  int ASSIGN = 113;
  /** RegularExpression Id. */
  int LT = 114;
  /** RegularExpression Id. */
  int BANG = 115;
  /** RegularExpression Id. */
  int TILDE = 116;
  /** RegularExpression Id. */
  int HOOK = 117;
  /** RegularExpression Id. */
  int COLON = 118;
  /** RegularExpression Id. */
  int EQ = 119;
  /** RegularExpression Id. */
  int LE = 120;
  /** RegularExpression Id. */
  int GE = 121;
  /** RegularExpression Id. */
  int NE = 122;
  /** RegularExpression Id. */
  int SC_OR = 123;
  /** RegularExpression Id. */
  int SC_AND = 124;
  /** RegularExpression Id. */
  int INCR = 125;
  /** RegularExpression Id. */
  int DECR = 126;
  /** RegularExpression Id. */
  int PLUS = 127;
  /** RegularExpression Id. */
  int MINUS = 128;
  /** RegularExpression Id. */
  int STAR = 129;
  /** RegularExpression Id. */
  int SLASH = 130;
  /** RegularExpression Id. */
  int BIT_AND = 131;
  /** RegularExpression Id. */
  int BIT_OR = 132;
  /** RegularExpression Id. */
  int XOR = 133;
  /** RegularExpression Id. */
  int REM = 134;
  /** RegularExpression Id. */
  int LSHIFT = 135;
  /** RegularExpression Id. */
  int PLUSASSIGN = 136;
  /** RegularExpression Id. */
  int MINUSASSIGN = 137;
  /** RegularExpression Id. */
  int STARASSIGN = 138;
  /** RegularExpression Id. */
  int SLASHASSIGN = 139;
  /** RegularExpression Id. */
  int ANDASSIGN = 140;
  /** RegularExpression Id. */
  int ORASSIGN = 141;
  /** RegularExpression Id. */
  int XORASSIGN = 142;
  /** RegularExpression Id. */
  int REMASSIGN = 143;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 144;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 145;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 146;
  /** RegularExpression Id. */
  int ELLIPSIS = 147;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 149;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"get\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"null\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"partial\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"set\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"var\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\">\"",
    "\"throws\"",
  };

}
