/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package net.chrizzly.csharp4netbeans.filetypes.cs.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int ABSTRACT = 6;
  /** RegularExpression Id. */
  int AS = 7;
  /** RegularExpression Id. */
  int BASE = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int BREAK = 10;
  /** RegularExpression Id. */
  int BYTE = 11;
  /** RegularExpression Id. */
  int CASE = 12;
  /** RegularExpression Id. */
  int CATCH = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int CHECKED = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CONST = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int DECIMAL = 19;
  /** RegularExpression Id. */
  int _DEFAULT = 20;
  /** RegularExpression Id. */
  int DELEGATE = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int DOUBLE = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int ENUM = 25;
  /** RegularExpression Id. */
  int EVENT = 26;
  /** RegularExpression Id. */
  int EXPLICIT = 27;
  /** RegularExpression Id. */
  int EXTERN = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FINALLY = 30;
  /** RegularExpression Id. */
  int FIXED = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int FOR = 33;
  /** RegularExpression Id. */
  int FOREACH = 34;
  /** RegularExpression Id. */
  int GET = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLICIT = 38;
  /** RegularExpression Id. */
  int IN = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int INTERFACE = 41;
  /** RegularExpression Id. */
  int INTERNAL = 42;
  /** RegularExpression Id. */
  int IS = 43;
  /** RegularExpression Id. */
  int LOCK = 44;
  /** RegularExpression Id. */
  int LONG = 45;
  /** RegularExpression Id. */
  int NAMESPACE = 46;
  /** RegularExpression Id. */
  int NEW = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int OBJECT = 49;
  /** RegularExpression Id. */
  int OPERATOR = 50;
  /** RegularExpression Id. */
  int OUT = 51;
  /** RegularExpression Id. */
  int OVERRIDE = 52;
  /** RegularExpression Id. */
  int PARAMS = 53;
  /** RegularExpression Id. */
  int PARTIAL = 54;
  /** RegularExpression Id. */
  int PRIVATE = 55;
  /** RegularExpression Id. */
  int PROTECTED = 56;
  /** RegularExpression Id. */
  int PUBLIC = 57;
  /** RegularExpression Id. */
  int READONLY = 58;
  /** RegularExpression Id. */
  int REF = 59;
  /** RegularExpression Id. */
  int RETURN = 60;
  /** RegularExpression Id. */
  int SBYTE = 61;
  /** RegularExpression Id. */
  int SEALED = 62;
  /** RegularExpression Id. */
  int SET = 63;
  /** RegularExpression Id. */
  int SHORT = 64;
  /** RegularExpression Id. */
  int SIZEOF = 65;
  /** RegularExpression Id. */
  int STACKALLOC = 66;
  /** RegularExpression Id. */
  int STATIC = 67;
  /** RegularExpression Id. */
  int STRING = 68;
  /** RegularExpression Id. */
  int STRUCT = 69;
  /** RegularExpression Id. */
  int SWITCH = 70;
  /** RegularExpression Id. */
  int THIS = 71;
  /** RegularExpression Id. */
  int THROW = 72;
  /** RegularExpression Id. */
  int TRUE = 73;
  /** RegularExpression Id. */
  int TRY = 74;
  /** RegularExpression Id. */
  int TYPEOF = 75;
  /** RegularExpression Id. */
  int UINT = 76;
  /** RegularExpression Id. */
  int ULONG = 77;
  /** RegularExpression Id. */
  int UNCHECKED = 78;
  /** RegularExpression Id. */
  int UNSAFE = 79;
  /** RegularExpression Id. */
  int USHORT = 80;
  /** RegularExpression Id. */
  int USING = 81;
  /** RegularExpression Id. */
  int VAR = 82;
  /** RegularExpression Id. */
  int VIRTUAL = 83;
  /** RegularExpression Id. */
  int VOID = 84;
  /** RegularExpression Id. */
  int VOLATILE = 85;
  /** RegularExpression Id. */
  int WHILE = 86;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 87;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 88;
  /** RegularExpression Id. */
  int HEX_LITERAL = 89;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 90;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 91;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 92;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 93;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 94;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 95;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 96;
  /** RegularExpression Id. */
  int STRING_LITERAL = 97;
  /** RegularExpression Id. */
  int IDENTIFIER = 98;
  /** RegularExpression Id. */
  int LETTER = 99;
  /** RegularExpression Id. */
  int PART_LETTER = 100;
  /** RegularExpression Id. */
  int LPAREN = 101;
  /** RegularExpression Id. */
  int RPAREN = 102;
  /** RegularExpression Id. */
  int LBRACE = 103;
  /** RegularExpression Id. */
  int RBRACE = 104;
  /** RegularExpression Id. */
  int LBRACKET = 105;
  /** RegularExpression Id. */
  int RBRACKET = 106;
  /** RegularExpression Id. */
  int SEMICOLON = 107;
  /** RegularExpression Id. */
  int COMMA = 108;
  /** RegularExpression Id. */
  int DOT = 109;
  /** RegularExpression Id. */
  int AT = 110;
  /** RegularExpression Id. */
  int ASSIGN = 111;
  /** RegularExpression Id. */
  int LT = 112;
  /** RegularExpression Id. */
  int BANG = 113;
  /** RegularExpression Id. */
  int TILDE = 114;
  /** RegularExpression Id. */
  int HOOK = 115;
  /** RegularExpression Id. */
  int COLON = 116;
  /** RegularExpression Id. */
  int EQ = 117;
  /** RegularExpression Id. */
  int LE = 118;
  /** RegularExpression Id. */
  int GE = 119;
  /** RegularExpression Id. */
  int NE = 120;
  /** RegularExpression Id. */
  int SC_OR = 121;
  /** RegularExpression Id. */
  int SC_AND = 122;
  /** RegularExpression Id. */
  int INCR = 123;
  /** RegularExpression Id. */
  int DECR = 124;
  /** RegularExpression Id. */
  int PLUS = 125;
  /** RegularExpression Id. */
  int MINUS = 126;
  /** RegularExpression Id. */
  int STAR = 127;
  /** RegularExpression Id. */
  int SLASH = 128;
  /** RegularExpression Id. */
  int BIT_AND = 129;
  /** RegularExpression Id. */
  int BIT_OR = 130;
  /** RegularExpression Id. */
  int XOR = 131;
  /** RegularExpression Id. */
  int REM = 132;
  /** RegularExpression Id. */
  int LSHIFT = 133;
  /** RegularExpression Id. */
  int PLUSASSIGN = 134;
  /** RegularExpression Id. */
  int MINUSASSIGN = 135;
  /** RegularExpression Id. */
  int STARASSIGN = 136;
  /** RegularExpression Id. */
  int SLASHASSIGN = 137;
  /** RegularExpression Id. */
  int ANDASSIGN = 138;
  /** RegularExpression Id. */
  int ORASSIGN = 139;
  /** RegularExpression Id. */
  int XORASSIGN = 140;
  /** RegularExpression Id. */
  int REMASSIGN = 141;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 142;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 143;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 144;
  /** RegularExpression Id. */
  int ELLIPSIS = 145;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 147;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 5>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"get\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"null\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"partial\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"set\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"var\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\">\"",
    "\"throws\"",
  };

}
